/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AccountRegisterIndexImport } from './routes/account/register/index'
import { Route as AccountProfileIndexImport } from './routes/account/profile/index'
import { Route as AccountLoginIndexImport } from './routes/account/login/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AccountRegisterIndexRoute = AccountRegisterIndexImport.update({
  id: '/account/register/',
  path: '/account/register/',
  getParentRoute: () => rootRoute,
} as any)

const AccountProfileIndexRoute = AccountProfileIndexImport.update({
  id: '/account/profile/',
  path: '/account/profile/',
  getParentRoute: () => rootRoute,
} as any)

const AccountLoginIndexRoute = AccountLoginIndexImport.update({
  id: '/account/login/',
  path: '/account/login/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/account/login/': {
      id: '/account/login/'
      path: '/account/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/account/profile/': {
      id: '/account/profile/'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileIndexImport
      parentRoute: typeof rootRoute
    }
    '/account/register/': {
      id: '/account/register/'
      path: '/account/register'
      fullPath: '/account/register'
      preLoaderRoute: typeof AccountRegisterIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account/login': typeof AccountLoginIndexRoute
  '/account/profile': typeof AccountProfileIndexRoute
  '/account/register': typeof AccountRegisterIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account/login': typeof AccountLoginIndexRoute
  '/account/profile': typeof AccountProfileIndexRoute
  '/account/register': typeof AccountRegisterIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/account/login/': typeof AccountLoginIndexRoute
  '/account/profile/': typeof AccountProfileIndexRoute
  '/account/register/': typeof AccountRegisterIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/account/login' | '/account/profile' | '/account/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/account/login' | '/account/profile' | '/account/register'
  id:
    | '__root__'
    | '/'
    | '/account/login/'
    | '/account/profile/'
    | '/account/register/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountLoginIndexRoute: typeof AccountLoginIndexRoute
  AccountProfileIndexRoute: typeof AccountProfileIndexRoute
  AccountRegisterIndexRoute: typeof AccountRegisterIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountLoginIndexRoute: AccountLoginIndexRoute,
  AccountProfileIndexRoute: AccountProfileIndexRoute,
  AccountRegisterIndexRoute: AccountRegisterIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/account/login/",
        "/account/profile/",
        "/account/register/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/account/login/": {
      "filePath": "account/login/index.tsx"
    },
    "/account/profile/": {
      "filePath": "account/profile/index.tsx"
    },
    "/account/register/": {
      "filePath": "account/register/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
